version: 2.1

orbs:
  android: circleci/android@2.3.0


jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run:
            name: Install OpenJDK 17
            command: |
              wget https://download.java.net/java/GA/jdk17.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
              sudo tar -zxvf openjdk-17.0.2_linux-x64_bin.tar.gz -C /usr/lib/jvm
              sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17.0.2/bin/java 100
              sudo update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/jdk-17.0.2/bin/jar 100
              sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-17.0.2/bin/javac 100
              sudo update-alternatives --set java /usr/lib/jvm/jdk-17.0.2/bin/java
              sudo update-alternatives --set jar /usr/lib/jvm/jdk-17.0.2/bin/jar
              sudo update-alternatives --set javac /usr/lib/jvm/jdk-17.0.2/bin/javac
              java -version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
workflows:
  test:
    jobs:
      - test